# Generated by Django 3.1.3 on 2021-02-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210131_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['step_created']},
        ),
    ]
