# Generated by Django 3.1.3 on 2021-02-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210204_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
