# Generated by Django 3.1.3 on 2021-02-20 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRecursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='projects.testrecursion', verbose_name='Родитель')),
            ],
        ),
    ]
