# Generated by Django 3.1.3 on 2021-02-22 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_testrecursion'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='sub_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_steps', to='projects.step', verbose_name='Родитель'),
        ),
    ]
