# Generated by Django 3.1.3 on 2020-12-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='subtext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
