# Generated by Django 3.1.3 on 2020-12-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('note', '0003_auto_20201201_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='account.CustomUser'),
        ),
    ]
