# Generated by Django 3.1.3 on 2020-12-08 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('note', '0005_auto_20201208_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='notecategory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='account.customuser'),
            preserve_default=False,
        ),
    ]
