# Generated by Django 3.1.3 on 2020-12-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_notecategory_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notecategory',
            options={'ordering': ['-id']},
        ),
    ]
