# Generated by Django 3.1.3 on 2020-12-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_auto_20201213_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notecategory',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='notecategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
